name: x86-linux

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install clang ninja-build --yes
 
    - name: Configure CMake
      run: cmake . -B build --preset clang -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Run benchmark
      shell: bash
      run: |
        mkdir data
        ./build/main

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: run_benchmark_linux_x64
        path: ${{github.workspace}}/build/main